name: Jean Emer
description: Personal website and blog
source: src
url: http://jcemer.com
permalink: :title.html
exclude: ["vendor"]
markdown: redcarpet
highlighter: pygments
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
assets:
  compress:
    css:  sass
    js:   uglifier
